### ISSUE TITLE
能否给TFormField中的Row增加backgroundColor选项

### ISSUE THREAD

**Issue by cn1001wang** [yichahucha/tform#6]
tform: ^0.9.3
---

设计稿给出的是背景为灰色，输入框为白色。我现在把Scaffold的background设置为灰色，但是TFormRow.input不支持传入color去自定义
```
TForm.builder(
                key: _formKey,
                rows: [ TFormRow.input(title: "姓名",)]
)
```

---

另外，能否支持输入框内容向右对齐，如web移动端框架Vant的截图
![image](https://user-images.githubusercontent.com/34416681/115361846-90005d80-a1f3-11eb-8657-1e1214dbf54d.png)

**Comment by yichahucha** [comment]
更新版本：0.9.6
1. 修改默认背景色为白色
2. row 的 textAlign 属性支持修改对齐方式 `textAlign: TextAlign.right`

**Comment by cn1001wang** [comment]
thank U! 我试过了非常完美。谢谢
