### ISSUE TITLE
能控制 requireStar 在文字前后的位置吗？

### ISSUE THREAD

**Issue by yandixuan** [yichahucha/tform#7]

**Comment by yichahucha** [comment]
更新版本：1.0.0
1. 使用 requireStar 默认在文字后添加星号
2. 不使用 requireStar 自己添加星号可以自动识别. `title: "* 预留手机号"`

**Comment by cn1001wang** [comment]
非常棒，刚好有这个需求😀

**Comment by cn1001wang** [comment]
![image](https://user-images.githubusercontent.com/34416681/115809832-67f54200-a41f-11eb-9ded-7337694ac205.png)
当title包含星号时，`formValidationErrors`验证会把*也给丢出来

**Comment by yichahucha** [comment]
1.0.1 已修复
